--// Kills & Killstreaks
--// No achievements ship pre-registered. Register your own via the admin
--// panel or directly in code, e.g.:
--
-- DuckAch.Registry.Register({
--     id          = "killstreak_5",
--     name        = "On Fire",
--     description = "Get a 5-kill streak without dying.",
--     rarity      = "uncommon",
--     secret      = false,
--     triggerType = "get_x_killstreak",
--     params      = { kills = 5 },
-- })
