--// Miscellaneous Achievements
--// No achievements ship pre-registered. Register your own via the admin
--// panel or directly in code, e.g.:
--
-- DuckAch.Registry.Register({
--     id          = "own_all_legendary",
--     name        = "Completionist",
--     description = "Unlock every legendary-rarity achievement.",
--     rarity      = "legendary",
--     secret      = false,
--     triggerType = "complete_rarity_x",
--     params      = { rarity = "legendary" },
-- })
--
-- See classes/achievement_class.lua's VALID_TYPES for the full list of available triggerTypes.
