--// Playtime & Progression
--// No achievements ship pre-registered. Register your own via the admin
--// panel or directly in code, e.g.:
--
-- DuckAch.Registry.Register({
--     id          = "playtime_20h",
--     name        = "Old Guard",
--     description = "Reach 20 hours of playtime on this server.",
--     rarity      = "rare",
--     secret      = false,
--     triggerType = "reach_playtime_hours",
--     params      = { hours = 20 },
-- })
