--// Social, Chat, Behavior
--// No achievements ship pre-registered. Register your own via the admin
--// panel or directly in code, e.g.:
--
-- DuckAch.Registry.Register({
--     id          = "say_hello",
--     name        = "Hello, World!",
--     description = "Say \"hello\" in chat.",
--     rarity      = "common",
--     secret      = false,
--     triggerType = "say_specific_phrase",
--     params      = { phrase = "hello", caseSensitive = false },
-- })
