--// Entity Spawns
--// Uses the model path (GetModel()) instead of classname.
--// E.g.: "models/props_junk/PopCan01a.mdl"
--//
--// No achievements ship pre-registered. Register your own via the admin
--// panel or directly in code, e.g.:
--
-- DuckAch.Registry.Register({
--     id          = "spawn_props_200",
--     name        = "Prop Enjoyer",
--     description = "Spawn 200 props.",
--     rarity      = "uncommon",
--     secret      = false,
--     triggerType = "spawn_x_entity_y_times",
--     params      = { classname = "any", times = 200 },
-- })
